---
title: "Data Visualization Sapun"
author: "Madison Pickett"
date: "5/8/2022"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
## DAY 3, AM, N2, 231
n1<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_AM_Day3NBDglucose.csv"
d_nbd_n2_AM_231<-read_csv(n1, col_names=TRUE)
d1<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_AM_Day3Draq5_nucleus.csv"
d_draq_n2_AM_231<-read_csv(d1, col_names=TRUE)

d_nbd_n2_AM_231_meanint<- d_nbd_n2_AM_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n2_AM_231<- d_draq_n2_AM_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N2_231_AM_Day3<- d_nbd_n2_AM_231_meanint$meanIntnbd1/d_draq_n2_AM_231$n
mean_tot_N2_231_AM_Day3<- (sum(d_nbd_n2_AM_231_meanint$meanIntnbd1/d_draq_n2_AM_231$n))/nrow(d_nbd_n2_AM_231_meanint)

```

```{r D3 RM}
## DAY 3, RM, N2, 231
n2<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_RM_Day3NBDglucose.csv"
d_nbd_n2_RM_231<-read_csv(n2, col_names=TRUE)
d2<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_RM_Day3Draq5_nucleus.csv"
d_draq_n2_RM_231<-read_csv(d2, col_names=TRUE)

d_nbd_n2_RM_231_meanint<- d_nbd_n2_RM_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n2_RM_231<- d_draq_n2_RM_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N2_231_RM_Day3<- d_nbd_n2_RM_231_meanint$meanIntnbd1/d_draq_n2_RM_231$n
mean_tot_N2_231_RM_Day3<- (sum(d_nbd_n2_RM_231_meanint$meanIntnbd1/d_draq_n2_RM_231$n))/nrow(d_nbd_n2_RM_231_meanint)
```

```{r D3 R}
## DAY 3, R, N2, 231
n3<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_R_Day3NBDglucose.csv"
d_nbd_n2_R_231<-read_csv(n3, col_names=TRUE)
d3<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_R_Day3Draq5_nucleus.csv"
d_draq_n2_R_231<-read_csv(d3, col_names=TRUE)

d_nbd_n2_R_231_meanint<- d_nbd_n2_R_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n2_R_231<- d_draq_n2_R_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N2_231_R_Day3<- d_nbd_n2_R_231_meanint$meanIntnbd1/d_draq_n2_R_231$n
mean_tot_N2_231_R_Day3<- (sum(d_nbd_n2_R_231_meanint$meanIntnbd1/d_draq_n2_R_231$n))/nrow(d_nbd_n2_R_231_meanint)
```

```{r D3 A}
## DAY 3, A, N2, 231
n4<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_A_Day3NBDglucose.csv"
d_nbd_n2_A_231<-read_csv(n4, col_names=TRUE)
d4<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_A_Day3Draq5_nucleus.csv"
d_draq_n2_A_231<-read_csv(d4, col_names=TRUE)

d_nbd_n2_A_231_meanint<- d_nbd_n2_A_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n2_A_231<- d_draq_n2_A_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N2_231_A_Day3<- d_nbd_n2_A_231_meanint$meanIntnbd1/d_draq_n2_A_231$n
mean_tot_N2_231_A_Day3<- (sum(d_nbd_n2_A_231_meanint$meanIntnbd1/d_draq_n2_A_231$n))/nrow(d_nbd_n2_A_231_meanint)
```

```{r D5 RM}
## DAY 5, RM, N2, 231
n5<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/RM_Day5_N2_231-nbd.csv"
d_nbd_n2_RM5_231<-read_csv(n5, col_names=TRUE)
d5<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/N2_Day%205_RM_231_Draq5_nucleus.csv"
d_draq_n2_RM5_231<-read_csv(d5, col_names=TRUE)

d_nbd_n2_RM5_231_meanint<- d_nbd_n2_RM5_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n2_RM5_231<- d_draq_n2_RM5_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N2_231_RM_Day5<- d_nbd_n2_RM5_231_meanint$meanIntnbd1/d_draq_n2_RM5_231$n
mean_tot_N2_231_RM_Day5<- (sum(d_nbd_n2_RM5_231_meanint$meanIntnbd1/d_draq_n2_RM5_231$n))/nrow(d_nbd_n2_RM5_231_meanint)
```

```{r D5 AM}
## DAY 5, AM, N2, 231
n6<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_AM_Day5NBDglucose.csv"
d_nbd_n2_AM5_231<-read_csv(n6, col_names=TRUE)
d6<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_AM_Day5Draq5_nucleus.csv"
d_draq_n2_AM5_231<-read_csv(d6, col_names=TRUE)

d_nbd_n2_AM5_231_meanint<- d_nbd_n2_AM5_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n2_AM5_231<- d_draq_n2_AM5_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N2_231_AM_Day5<- d_nbd_n2_AM5_231_meanint$meanIntnbd1/d_draq_n2_AM5_231$n
mean_tot_N2_231_AM_Day5<- (sum(d_nbd_n2_AM5_231_meanint$meanIntnbd1/d_draq_n2_AM5_231$n))/nrow(d_nbd_n2_AM5_231_meanint)
```

```{r D5 A}
## DAY 5, A, N2, 231
n7<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_A_Day5NBDglucose.csv"
d_nbd_n2_A5_231<-read_csv(n7, col_names=TRUE)
d7<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_A_Day5Draq5_nucleus.csv"
d_draq_n2_A5_231<-read_csv(d7, col_names=TRUE)

d_nbd_n2_A5_231_meanint<- d_nbd_n2_A5_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n2_A5_231<- d_draq_n2_A5_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N2_231_A_Day5<- d_nbd_n2_A5_231_meanint$meanIntnbd1/d_draq_n2_A5_231$n
mean_tot_N2_231_A_Day5<- (sum(d_nbd_n2_A5_231_meanint$meanIntnbd1/d_draq_n2_A5_231$n))/nrow(d_nbd_n2_A5_231_meanint)
```

```{r D5 R}
## DAY 5, R, N2, 231
n8<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_R_Day5NBDglucose.csv"
d_nbd_n2_R5_231<-read_csv(n8, col_names=TRUE)
d8<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/MyExptN2_231_R_Day5Draq5_nucleus.csv"
d_draq_n2_R5_231<-read_csv(d8, col_names=TRUE)

d_nbd_n2_R5_231_meanint<- d_nbd_n2_R5_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n2_R5_231<- d_draq_n2_R5_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N2_231_R_Day5<- d_nbd_n2_R5_231_meanint$meanIntnbd1/d_draq_n2_R5_231$n

mean_tot_N2_231_R_Day5<- (sum(d_nbd_n2_R5_231_meanint$meanIntnbd1/d_draq_n2_R5_231$n))/nrow(d_nbd_n2_R5_231_meanint)
```

```{r D5 R N1}
## DAY 5, R, N2, 231
library(tidyverse)
n9<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/R_DAY5_231_N1_NBDglucose.csv"
d_nbd_n1_R5_231<-read_csv(n9, col_names=TRUE)
d9<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/R_DAY5_231_N1_Draq5_nucleus.csv"
d_draq_n1_R5_231<-read_csv(d9, col_names=TRUE)

d_nbd_n1_R5_231_meanint<- d_nbd_n1_R5_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n1_R5_231<- d_draq_n1_R5_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N1_231_R_Day5<- d_nbd_n1_R5_231_meanint$meanIntnbd1/d_draq_n1_R5_231$n

mean_tot_N1_231_R_Day5<- (sum(d_nbd_n1_R5_231_meanint$meanIntnbd1/d_draq_n1_R5_231$n))/nrow(d_nbd_n1_R5_231_meanint)
```

```{r D5 RM N1}
library(tidyverse)
n10<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/RM_DAY5_231_N1_NBDglucose.csv"
d_nbd_n1_RM5_231<-read_csv(n10, col_names=TRUE)
d10<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/RM_DAY5_231_N1_Draq5_nucleus.csv"
d_draq_n1_RM5_231<-read_csv(d10, col_names=TRUE)

d_nbd_n1_RM5_231_meanint<- d_nbd_n1_RM5_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n1_RM5_231<- d_draq_n1_RM5_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N1_231_RM_Day5<- d_nbd_n1_RM5_231_meanint$meanIntnbd1/d_draq_n1_RM5_231$n

mean_tot_N1_231_RM_Day5<- (sum(d_nbd_n1_RM5_231_meanint$meanIntnbd1/d_draq_n1_RM5_231$n))/nrow(d_nbd_n1_RM5_231_meanint)
```
```{r D5 AM N1}

library(tidyverse)
n11<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/AM_DAY5_231_N1_NBDglucose.csv"
d_nbd_n1_AM5_231<-read_csv(n11, col_names=TRUE)
d11<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/AM_DAY5_231_N1_Draq5_nucleus.csv"
d_draq_n1_AM5_231<-read_csv(d11, col_names=TRUE)

d_nbd_n1_AM5_231_meanint<- d_nbd_n1_AM5_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n1_AM5_231<- d_draq_n1_AM5_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N1_231_AM_Day5<- d_nbd_n1_AM5_231_meanint$meanIntnbd1/d_draq_n1_AM5_231$n

mean_tot_N1_231_AM_Day5<- (sum(d_nbd_n1_AM5_231_meanint$meanIntnbd1/d_draq_n1_AM5_231$n))/nrow(d_nbd_n1_AM5_231_meanint)
```
```{r D5 A N1}
library(tidyverse)
n12<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/A_DAY5_231_N1_realNBDglucose.csv"
d_nbd_n1_A5_231<-read_csv(n12, col_names=TRUE)
d12<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/A_DAY5_231_N1_realDraq5_nucleus.csv"
d_draq_n1_A5_231<-read_csv(d12, col_names=TRUE)

d_nbd_n1_A5_231_meanint<- d_nbd_n1_A5_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n1_A5_231<- d_draq_n1_A5_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N1_231_A_Day5<- d_nbd_n1_A5_231_meanint$meanIntnbd1/d_draq_n1_A5_231$n

mean_tot_N1_231_A_Day5<- (sum(d_nbd_n1_A5_231_meanint$meanIntnbd1/d_draq_n1_A5_231$n))/nrow(d_nbd_n1_A5_231_meanint)
```
```{r D3 A N1}
library(tidyverse)
n13<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/A_DAY3_231_N1_NBDglucose.csv"
d_nbd_n1_A3_231<-read_csv(n13, col_names=TRUE)
d13<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/A_DAY3_231_N1_Draq5_nucleus.csv"
d_draq_n1_A3_231<-read_csv(d13, col_names=TRUE)

d_nbd_n1_A3_231_meanint<- d_nbd_n1_A3_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n1_A3_231<- d_draq_n1_A3_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N1_231_A_Day3<- d_nbd_n1_A3_231_meanint$meanIntnbd1/d_draq_n1_A3_231$n

mean_tot_N1_231_A_Day3<- (sum(d_nbd_n1_A3_231_meanint$meanIntnbd1/d_draq_n1_A3_231$n))/nrow(d_nbd_n1_A3_231_meanint)
```

```{r D3 AM N1}
library(tidyverse)
n14<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/AM_DAY3_231_N1_NBDglucose.csv"
d_nbd_n1_AM3_231<-read_csv(n14, col_names=TRUE)
d14<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/AM_DAY3_231_N1_Draq5_nucleus.csv"
d_draq_n1_AM3_231<-read_csv(d14, col_names=TRUE)

d_nbd_n1_AM3_231_meanint<- d_nbd_n1_AM3_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n1_AM3_231<- d_draq_n1_AM3_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N1_231_AM_Day3<- d_nbd_n1_AM3_231_meanint$meanIntnbd1/d_draq_n1_AM3_231$n

mean_tot_N1_231_AM_Day3<- (sum(d_nbd_n1_AM3_231_meanint$meanIntnbd1/d_draq_n1_AM3_231$n))/nrow(d_nbd_n1_AM3_231_meanint)
```
```{r D3 RM N1}
library(tidyverse)
n15<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/RM_DAY3_231_N1_realNBDglucose.csv"
d_nbd_n1_RM3_231<-read_csv(n15, col_names=TRUE)
d15<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/RM_DAY3_231_N1_realDraq5_nucleus.csv"
d_draq_n1_RM3_231<-read_csv(d15, col_names=TRUE)

d_nbd_n1_RM3_231_meanint<- d_nbd_n1_RM3_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n1_RM3_231<- d_draq_n1_RM3_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N1_231_RM_Day3<- d_nbd_n1_RM3_231_meanint$meanIntnbd1/d_draq_n1_RM3_231$n

mean_tot_N1_231_RM_Day3<- (sum(d_nbd_n1_RM3_231_meanint$meanIntnbd1/d_draq_n1_RM3_231$n))/nrow(d_nbd_n1_RM3_231_meanint)
```

```{r D3 R N1}
library(tidyverse)
n16<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/R_DAY3_231_N1_NBDglucose.csv"
d_nbd_n1_R3_231<-read_csv(n15, col_names=TRUE)
d16<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/R_DAY3_231_N1_Draq5_nucleus.csv"
d_draq_n1_R3_231<-read_csv(d15, col_names=TRUE)

d_nbd_n1_R3_231_meanint<- d_nbd_n1_R3_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n1_R3_231<- d_draq_n1_R3_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N1_231_R_Day3<- d_nbd_n1_R3_231_meanint$meanIntnbd1/d_draq_n1_R3_231$n

mean_tot_N1_231_R_Day3<- (sum(d_nbd_n1_R3_231_meanint$meanIntnbd1/d_draq_n1_R3_231$n))/nrow(d_nbd_n1_R3_231_meanint)
```



```{r D5 R N3}
## DAY 5, R, N3, 231
library(tidyverse)
n17<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/R_DAY5_231_N3_NBDglucose.csv"
d_nbd_n3_R5_231<-read_csv(n17, col_names=TRUE)
d17<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/R_DAY5_231_N3_Draq5_nucleus.csv"
d_draq_n3_R5_231<-read_csv(d17, col_names=TRUE)

d_nbd_n3_R5_231_meanint<- d_nbd_n3_R5_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n3_R5_231<- d_draq_n3_R5_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N3_231_R_Day5<- d_nbd_n3_R5_231_meanint$meanIntnbd1/d_draq_n3_R5_231$n

mean_tot_N3_231_R_Day5<- (sum(d_nbd_n3_R5_231_meanint$meanIntnbd1/d_draq_n3_R5_231$n))/nrow(d_nbd_n3_R5_231_meanint)
```

```{r D5 RM N3}
library(tidyverse)
n18<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/RM_DAY5_231_N3_NBDglucose.csv"
d_nbd_n3_RM5_231<-read_csv(n18, col_names=TRUE)
d18<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/RM_DAY5_231_N3_Draq5_nucleus.csv"
d_draq_n3_RM5_231<-read_csv(d18, col_names=TRUE)

d_nbd_n3_RM5_231_meanint<- d_nbd_n3_RM5_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n3_RM5_231<- d_draq_n3_RM5_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N3_231_RM_Day5<- d_nbd_n3_RM5_231_meanint$meanIntnbd1/d_draq_n3_RM5_231$n

mean_tot_N3_231_RM_Day5<- (sum(d_nbd_n3_RM5_231_meanint$meanIntnbd1/d_draq_n3_RM5_231$n))/nrow(d_nbd_n3_RM5_231_meanint)
```

```{r D5 AM N3}

library(tidyverse)
n19<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/AM_DAY5_231_N3_NBDglucose.csv"
d_nbd_n3_AM5_231<-read_csv(n19, col_names=TRUE)
d19<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/AM_DAY5_231_N3_Draq5_nucleus.csv"
d_draq_n3_AM5_231<-read_csv(d19, col_names=TRUE)

d_nbd_n3_AM5_231_meanint<- d_nbd_n3_AM5_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n3_AM5_231<- d_draq_n3_AM5_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N3_231_AM_Day5<- d_nbd_n3_AM5_231_meanint$meanIntnbd1/d_draq_n3_AM5_231$n

mean_tot_N3_231_AM_Day5<- (sum(d_nbd_n3_AM5_231_meanint$meanIntnbd1/d_draq_n3_AM5_231$n))/nrow(d_nbd_n3_AM5_231_meanint)
```

```{r D5 A N3}
library(tidyverse)
n20<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/A_DAY5_231_N3_NBDglucose.csv"
d_nbd_n3_A5_231<-read_csv(n20, col_names=TRUE)
d20<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/A_DAY5_231_N3_Draq5_nucleus.csv"
d_draq_n3_A5_231<-read_csv(d20, col_names=TRUE)

d_nbd_n3_A5_231_meanint<- d_nbd_n3_A5_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n3_A5_231<- d_draq_n3_A5_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N3_231_A_Day5<- d_nbd_n3_A5_231_meanint$meanIntnbd1/d_draq_n3_A5_231$n

mean_tot_N3_231_A_Day5<- (sum(d_nbd_n3_A5_231_meanint$meanIntnbd1/d_draq_n3_A5_231$n))/nrow(d_nbd_n3_A5_231_meanint)
```

```{r D3 A N3}
library(tidyverse)
n21<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/A_DAY3_231_N3_NBDglucose.csv"
d_nbd_n3_A3_231<-read_csv(n21, col_names=TRUE)
d21<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/A_DAY3_231_N3_Draq5_nucleus.csv"
d_draq_n3_A3_231<-read_csv(d21, col_names=TRUE)

d_nbd_n3_A3_231_meanint<- d_nbd_n3_A3_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n3_A3_231<- d_draq_n3_A3_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N3_231_A_Day3<- d_nbd_n3_A3_231_meanint$meanIntnbd1/d_draq_n3_A3_231$n

mean_tot_N3_231_A_Day3<- (sum(d_nbd_n3_A3_231_meanint$meanIntnbd1/d_draq_n3_A3_231$n))/nrow(d_nbd_n3_A3_231_meanint)
```

```{r D3 AM N3}
library(tidyverse)
n22<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/AM_DAY3_231_N3_NBDglucose.csv"
d_nbd_n3_AM3_231<-read_csv(n22, col_names=TRUE)
d22<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/AM_DAY3_231_N3_Draq5_nucleus.csv"
d_draq_n3_AM3_231<-read_csv(d22, col_names=TRUE)

d_nbd_n3_AM3_231_meanint<- d_nbd_n3_AM3_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n3_AM3_231<- d_draq_n3_AM3_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N3_231_AM_Day3<- d_nbd_n3_AM3_231_meanint$meanIntnbd1/d_draq_n3_AM3_231$n

mean_tot_N3_231_AM_Day3<- (sum(d_nbd_n3_AM3_231_meanint$meanIntnbd1/d_draq_n3_AM3_231$n))/nrow(d_nbd_n3_AM3_231_meanint)
```

```{r D3 RM N3}
library(tidyverse)
n23<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/RM_DAY3_231_N3_NBDglucose.csv"
d_nbd_n3_RM3_231<-read_csv(n23, col_names=TRUE)
d23<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/RM_DAY3_231_N3_Draq5_nucleus.csv"
d_draq_n3_RM3_231<-read_csv(d23, col_names=TRUE)

d_nbd_n3_RM3_231_meanint<- d_nbd_n3_RM3_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n3_RM3_231<- d_draq_n3_RM3_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N3_231_RM_Day3<- d_nbd_n3_RM3_231_meanint$meanIntnbd1/d_draq_n3_RM3_231$n

mean_tot_N3_231_RM_Day3<- (sum(d_nbd_n3_RM3_231_meanint$meanIntnbd1/d_draq_n3_RM3_231$n))/nrow(d_nbd_n3_RM3_231_meanint)
```

```{r D3 R N3}
library(tidyverse)
n24<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/R_DAY3_231_N3_NBDglucose.csv"
d_nbd_n3_R3_231<-read_csv(n24, col_names=TRUE)
d24<- "https://raw.githubusercontent.com/mrpickett26/NBD_glucose_Analysis/main/R_DAY3_231_N3_Draq5_nucleus.csv"
d_draq_n3_R3_231<-read_csv(d24, col_names=TRUE)

d_nbd_n3_R3_231_meanint<- d_nbd_n3_R3_231%>%
  group_by(ImageNumber)%>%
  summarize(meanIntnbd1= mean(Intensity_IntegratedIntensity_NBDglucose, na.rm=TRUE))

d_draq_n3_R3_231<- d_draq_n3_R3_231%>%
  group_by(ImageNumber)%>%
  summarize(n=n())

mean_N3_231_R_Day3<- d_nbd_n3_R3_231_meanint$meanIntnbd1/d_draq_n3_R3_231$n

mean_tot_N3_231_R_Day3<- (sum(d_nbd_n3_R3_231_meanint$meanIntnbd1/d_draq_n3_R3_231$n))/nrow(d_nbd_n3_R3_231_meanint)
```

```{r plot}
#plot the data
mean_total_Aligned_Day3<- (mean_tot_N1_231_A_Day3+ mean_tot_N2_231_A_Day3+ mean_tot_N3_231_A_Day3)/3
conc_day3_A<- c(mean_N1_231_A_Day3, mean_N2_231_A_Day3, mean_N3_231_A_Day3)
mean_total_Random_Day3<- (mean_tot_N1_231_R_Day3+ mean_tot_N2_231_R_Day3+ mean_tot_N3_231_R_Day3)/3
conc_day3_R<-c(mean_N1_231_R_Day3,mean_N2_231_R_Day3, mean_N3_231_R_Day3)
mean_total_AlignedMat_Day3<-(mean_tot_N1_231_AM_Day3+mean_tot_N2_231_AM_Day3+mean_tot_N3_231_AM_Day3)/3
conc_day3_AM<- c(mean_N1_231_AM_Day3, mean_N2_231_AM_Day3, mean_N3_231_AM_Day3)
mean_total_RandomMat_Day3<-(mean_tot_N1_231_RM_Day3+mean_tot_N2_231_RM_Day3+mean_tot_N3_231_RM_Day3)/3
conc_day3_RM<- c(mean_N1_231_RM_Day3, mean_N2_231_RM_Day3, mean_N3_231_RM_Day3)


mean_total_Aligned_Day5<- (mean_tot_N1_231_A_Day5+ mean_tot_N2_231_A_Day5+ mean_tot_N3_231_A_Day5)/3
conc_day5_A<-c(mean_N1_231_A_Day5, mean_N2_231_A_Day5, mean_N3_231_A_Day5)
mean_total_Random_Day5<- (mean_tot_N1_231_R_Day5+ mean_tot_N2_231_R_Day5+ mean_tot_N3_231_R_Day5)/3
conc_day5_R<-c(mean_N1_231_R_Day5, mean_N2_231_R_Day5, mean_N3_231_R_Day5)
mean_total_AlignedMat_Day5<-(mean_tot_N1_231_AM_Day5+mean_tot_N2_231_AM_Day5+mean_tot_N3_231_R_Day5)/3
conc_day5_AM<-c(mean_N1_231_AM_Day5, mean_N2_231_AM_Day5, mean_N3_231_AM_Day5)
mean_total_RandomMat_Day5<-(mean_tot_N1_231_RM_Day5+mean_tot_N2_231_RM_Day5+mean_tot_N3_231_RM_Day5)/3
conc_day5_RM<-c(mean_N1_231_RM_Day5, mean_N2_231_RM_Day5, mean_N3_231_RM_Day5)

df3<- c(mean_total_Random_Day3, mean_total_Aligned_Day3, mean_total_RandomMat_Day3, mean_total_AlignedMat_Day3)
df5<- c(mean_total_Random_Day5, mean_total_Aligned_Day5, mean_total_RandomMat_Day5, mean_total_AlignedMat_Day5)
df_total<- cbind(df3,df5)
rownames(df_total) <- c('Aligned','Random','Aligned_Mat', 'Random_Mat')
colnames(df_total)<- c('Day3', 'Day5')
df3_conc<-cbind(conc_day3_A,conc_day3_R,conc_day3_AM,conc_day3_RM)
colnames(df3_conc) <- c('Aligned','Random','Aligned_Mat', 'Random_Mat')

df5_conc<-cbind(conc_day5_A,conc_day5_R,conc_day5_AM,conc_day5_RM)
colnames(df5_conc) <- c('Aligned','Random','Aligned_Mat', 'Random_Mat')

total<-cbind.data.frame(df3_conc, df5_conc)
total<-as.data.frame(total)
se <- function(x) sqrt(var(x) / length(x))
std_errs<-c(se(conc_day3_A), se(conc_day3_R), se(conc_day3_AM), se(conc_day3_RM), se(conc_day5_A), se(conc_day5_R), se(conc_day5_AM), se(conc_day5_RM))
bar_plot_fig<-barplot(df_total, 
        col=colors()[c(23,89,12,17)] , 
        border="white", 
        font.axis=2, 
        beside=T, 
        legend=rownames(df_total), 
        xlab='group',
        ylab="Integrated NBD Intensity per Cell",
        xlim = c(0, 18),
        font.lab=2)
arrows(bar_plot_fig, df_total+std_errs, bar_plot_fig, df_total-std_errs, angle=90, code=3, length=0.06, col="black")

R_A_Day3<- t.test(conc_day3_A,conc_day3_R)
R_A_Day3
summary(R_A_Day3)
RM_AM_Day3<- t.test(conc_day3_AM, conc_day3_RM)
RM_AM_Day3

R_A_Day5<- t.test(conc_day5_A,conc_day5_R)
R_A_Day5
RM_AM_Day5<- t.test(conc_day5_AM, conc_day5_RM)
RM_AM_Day5

# total%>%
#   .id = "id" %>%
#   ggplot(aes()) +
#   geom_bar(aes(fill = id), stat = "identity", position = "dodge2", width = 0.5) +
#   geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd, width = 0.1, colour = id)) 
# 
# library(reshape2)
# library(ggplot2)
# total<-cbind.data.frame(df3_conc, df5_conc)
# total<-as.data.frame(total)


# barplot(df3, main="Average Integrated Intensity per Nuclei 231 Day 3", names.arg =c( "Random","Aligned","RM","AM"), ylab="Integrated Intensity", col=c("#eb8060", "#b9e38d", "#a1e9f0", "#d9b1f0"))
# 
# barplot(df5, main="Average Integrated Intensity per Nuclei 231 Day 5", names.arg =c("Random","Aligned","RM","AM"), ylab="Integrated Intensity", col=c("#eb8060", "#b9e38d", "#a1e9f0", "#d9b1f0"))
# 

```



```{r plot}
#plot the data
library(cowplot)
df_nbd_A3<-as_tibble(c(d_nbd_n1_A3_231_meanint$meanIntnbd1,d_nbd_n2_A_231_meanint$meanIntnbd1, d_nbd_n3_A3_231_meanint$meanIntnbd1))
df_dapi<- as_tibble(c(d_draq_n1_A3_231$n, d_draq_n2_A_231$n, d_draq_n3_A3_231$n))
df_num_A3<- as_tibble(c(d_nbd_n1_A3_231_meanint$ImageNumber,d_nbd_n2_A_231_meanint$ImageNumber, d_nbd_n3_A3_231_meanint$ImageNumber))
df_sum_A3<- bind_cols(df_num_A3, df_num_A3, df_dapi, df_nbd_A3)
colnames(df_sum_A3) <- c('Image_Number','Image__Number','num_of_nuclei', 'intensity')


df_sum_A3<- as_data_frame(df_sum_A3)
tit_A3<-"Heat Map and Size Plot for NBD Glucose Intensity and Number of Nuclei Aligned Day 3"
fig_A3<-ggplot(df_sum_A3, aes(x= Image_Number, y = Image__Number))+
   geom_tile(fill="white", color = "red") +
  geom_point(aes(color = intensity, size = num_of_nuclei))+
  scale_size_continuous(range = c(1,10))+labs(title = str_wrap(tit_A3, 40))
fig_A3

## RANDOM day 3
df_nbd_R3<-as_tibble(c(d_nbd_n1_R3_231_meanint$meanIntnbd1,d_nbd_n2_R_231_meanint$meanIntnbd1, d_nbd_n3_R3_231_meanint$meanIntnbd1))
dfR3_dapi<- as_tibble(c(d_draq_n1_R3_231$n, d_draq_n2_R_231$n, d_draq_n3_R3_231$n))
df_num_R3<- as_tibble(c(d_nbd_n1_R3_231_meanint$ImageNumber,d_nbd_n2_R_231_meanint$ImageNumber, d_nbd_n3_R3_231_meanint$ImageNumber))
df_sum_R3<- bind_cols(df_num_R3, df_num_R3, dfR3_dapi, df_nbd_R3)
colnames(df_sum_R3) <- c('Image_Number','Image__Number','num_of_nuclei', 'intensity')


df_sum_R3<- as_data_frame(df_sum_R3)
tit_R3<-"Heat Map and Size Plot for NBD Glucose Intensity and Number of Nuclei Random Day 3"
fig_R3<-ggplot(df_sum_R3, aes(x= Image_Number, y = Image__Number))+
   geom_tile(fill="white", color = "red") +
  geom_point(aes(color = intensity, size = num_of_nuclei))+
  scale_size_continuous(range = c(1,7))+labs(title = str_wrap(tit_R3, 40))
fig_R3


##RM Day 3
df_nbd_RM3<-as_tibble(c(d_nbd_n1_RM3_231_meanint$meanIntnbd1,d_nbd_n2_RM_231_meanint$meanIntnbd1, d_nbd_n3_RM3_231_meanint$meanIntnbd1))
dfRM3_dapi<- as_tibble(c(d_draq_n1_RM3_231$n, d_draq_n2_RM_231$n, d_draq_n3_RM3_231$n))
df_num_RM3<- as_tibble(c(d_nbd_n1_RM3_231_meanint$ImageNumber,d_nbd_n2_RM_231_meanint$ImageNumber, d_nbd_n3_RM3_231_meanint$ImageNumber))
df_sum_RM3<- bind_cols(df_num_RM3, df_num_RM3, dfRM3_dapi, df_nbd_RM3)
colnames(df_sum_RM3) <- c('Image_Number','Image__Number','num_of_nuclei', 'intensity')

df_sum_RM3<- as_data_frame(df_sum_RM3)
tit_RM3<-"Heat Map and Size Plot for NBD Glucose Intensity and Number of Nuclei Random Matrigel Day 3"
fig_RM3<-ggplot(df_sum_RM3, aes(x= Image_Number, y = Image__Number))+
   geom_tile(fill="white", color = "red") +
  geom_point(aes(color = intensity, size = num_of_nuclei))+
  scale_size_continuous(range = c(1,9))+labs(title = str_wrap(tit_RM3, 40))
fig_RM3

## Aligned Matrigel Day 3
df_nbd_AM3<-as_tibble(c(d_nbd_n1_AM3_231_meanint$meanIntnbd1,d_nbd_n2_AM_231_meanint$meanIntnbd1, d_nbd_n3_AM3_231_meanint$meanIntnbd1))
dfAM3_dapi<- as_tibble(c(d_draq_n1_AM3_231$n, d_draq_n2_AM_231$n, d_draq_n3_AM3_231$n))
df_num_AM3<- as_tibble(c(d_nbd_n1_AM3_231_meanint$ImageNumber,d_nbd_n2_AM_231_meanint$ImageNumber, d_nbd_n3_AM3_231_meanint$ImageNumber))
df_sum_AM3<- bind_cols(df_num_AM3, df_num_AM3, dfAM3_dapi, df_nbd_AM3)
colnames(df_sum_AM3) <- c('Image_Number','Image__Number','num_of_nuclei', 'intensity')

df_sum_AM3<- as_data_frame(df_sum_AM3)
tit_AM3<-"Heat Map and Size Plot for NBD Glucose Intensity and Number of Nuclei Aligned Matrigel Day 3"
fig_AM3<-ggplot(df_sum_AM3, aes(x= Image_Number, y = Image__Number))+
   geom_tile(fill="white", color = "red") +
  geom_point(aes(color = intensity, size = num_of_nuclei))+
  scale_size_continuous(range = c(1,9))+labs(title = str_wrap(tit_AM3, 40))
fig_AM3

plot_grid(fig_A3, fig_R3, labels = c('A', 'R'))
plot_grid(fig_AM3, fig_RM3, labels = c('AM', 'RM'))


```

```{r plot}
#plot the data Day5
library(cowplot)
df_nbd_A5<-as_tibble(c(d_nbd_n1_A5_231_meanint$meanIntnbd1,d_nbd_n2_A5_231_meanint$meanIntnbd1, d_nbd_n3_A5_231_meanint$meanIntnbd1))
df_dapi_A5<- as_tibble(c(d_draq_n1_A5_231$n, d_draq_n2_A5_231$n, d_draq_n3_A5_231$n))
df_num_A5<- as_tibble(c(d_nbd_n1_A5_231_meanint$ImageNumber,d_nbd_n2_A5_231_meanint$ImageNumber, d_nbd_n3_A5_231_meanint$ImageNumber))
df_sum_A5<- bind_cols(df_num_A5, df_num_A5, df_dapi_A5, df_nbd_A5)
colnames(df_sum_A5) <- c('Image_Number','Image__Number','num_of_nuclei', 'intensity')


df_sum_A5<- as_data_frame(df_sum_A5)
tit_A5<-"Heat Map and Size Plot for NBD Glucose Intensity and Number of Nuclei Aligned Day 5"
fig_A5<-ggplot(df_sum_A5, aes(x= Image_Number, y = Image__Number))+
   geom_tile(fill="white", color = "red") +
  geom_point(aes(color = intensity, size = num_of_nuclei))+
  scale_size_continuous(range = c(1,10))+labs(title = str_wrap(tit_A5, 40))
fig_A5

## RANDOM day 5
df_nbd_R5<-as_tibble(c(d_nbd_n1_R5_231_meanint$meanIntnbd1,d_nbd_n2_R5_231_meanint$meanIntnbd1, d_nbd_n3_R5_231_meanint$meanIntnbd1))
dfR5_dapi<- as_tibble(c(d_draq_n1_R5_231$n, d_draq_n2_R5_231$n, d_draq_n3_R5_231$n))
df_num_R5<- as_tibble(c(d_nbd_n1_R5_231_meanint$ImageNumber,d_nbd_n2_R5_231_meanint$ImageNumber, d_nbd_n3_R5_231_meanint$ImageNumber))
df_sum_R5<- bind_cols(df_num_R5, df_num_R5, dfR5_dapi, df_nbd_R5)
colnames(df_sum_R5) <- c('Image_Number','Image__Number','num_of_nuclei', 'intensity')


df_sum_R5<- as_data_frame(df_sum_R5)
tit_R5<-"Heat Map and Size Plot for NBD Glucose Intensity and Number of Nuclei Random Day 5"
fig_R5<-ggplot(df_sum_R5, aes(x= Image_Number, y = Image__Number))+
   geom_tile(fill="white", color = "red") +
  geom_point(aes(color = intensity, size = num_of_nuclei))+
  scale_size_continuous(range = c(1,10))+labs(title = str_wrap(tit_R5, 40))
fig_R5


##RM Day 3
df_nbd_RM5<-as_tibble(c(d_nbd_n1_RM5_231_meanint$meanIntnbd1,d_nbd_n2_RM5_231_meanint$meanIntnbd1, d_nbd_n3_RM5_231_meanint$meanIntnbd1))
dfRM5_dapi<- as_tibble(c(d_draq_n1_RM5_231$n, d_draq_n2_RM5_231$n, d_draq_n3_RM5_231$n))
df_num_RM5<- as_tibble(c(d_nbd_n1_RM5_231_meanint$ImageNumber,d_nbd_n2_RM5_231_meanint$ImageNumber, d_nbd_n3_RM5_231_meanint$ImageNumber))
df_sum_RM5<- bind_cols(df_num_RM5, df_num_RM5, dfRM5_dapi, df_nbd_RM5)
colnames(df_sum_RM5) <- c('Image_Number','Image__Number','num_of_nuclei', 'intensity')

df_sum_RM5<- as_data_frame(df_sum_RM5)
tit_RM5<-"Heat Map and Size Plot for NBD Glucose Intensity and Number of Nuclei Random Matrigel Day 5"
fig_RM5<-ggplot(df_sum_RM5, aes(x= Image_Number, y = Image__Number))+
   geom_tile(fill="white", color = "red") +
  geom_point(aes(color = intensity, size = num_of_nuclei))+
  scale_size_continuous(range = c(1,10))+labs(title = str_wrap(tit_RM5, 40))
fig_RM5

## Aligned Matrigel Day 
df_nbd_AM5<-as_tibble(c(d_nbd_n1_AM5_231_meanint$meanIntnbd1,d_nbd_n2_AM5_231_meanint$meanIntnbd1, d_nbd_n3_AM5_231_meanint$meanIntnbd1))
dfAM5_dapi<- as_tibble(c(d_draq_n1_AM5_231$n, d_draq_n2_AM5_231$n, d_draq_n3_AM5_231$n))
df_num_AM5<- as_tibble(c(d_nbd_n1_AM5_231_meanint$ImageNumber,d_nbd_n2_AM5_231_meanint$ImageNumber, d_nbd_n3_AM5_231_meanint$ImageNumber))
df_sum_AM5<- bind_cols(df_num_AM5, df_num_AM5, dfAM5_dapi, df_nbd_AM5)
colnames(df_sum_AM5) <- c('Image_Number','Image__Number','num_of_nuclei', 'intensity')

df_sum_AM5<- as_data_frame(df_sum_AM5)
tit_AM5<-"Heat Map and Size Plot for NBD Glucose Intensity and Number of Nuclei Aligned Matrigel Day 5"
fig_AM5<-ggplot(df_sum_AM5, aes(x= Image_Number, y = Image__Number))+
   geom_tile(fill="white", color = "red") +
  geom_point(aes(color = intensity, size = num_of_nuclei))+
  scale_size_continuous(range = c(1,9))+labs(title = str_wrap(tit_AM5, 40))
fig_AM5

plot_grid(fig_A5, fig_R5, labels = c('A', 'R'))
plot_grid(fig_AM5, fig_RM5, labels = c('AM', 'RM'))


```


